title: 爱发电的猛男妙妙屋欢迎您！
# 左侧栏名字
author_name: Humeng

# 左侧栏标签，只能两个
tag1: 喜欢探索
tag2: 喜欢学习

# 左侧栏Github连接
github_url: https://github.com/humengofchina

# 左侧栏座右铭，分两句
motto_prev: 穷则独善其身，达则兼济天下
motto_last: “一个简简单单普普通通平平庸庸的男孩”

# 小站部署日期（运营时间）
public_date: 2023-05-20

# 左侧栏菜单
menu:
  - [小站首页, 'meng-beta.vercel.app/', 'icon-shouye']
  - [个人日志, 'themes/hexo-theme-cola-master/source/imgs/log', 'icon-rizhi']
  - [友情链接, 'themes/hexo-theme-cola-master/source/imgs/link', 'icon-youqinglianjie']
  - ['关于自己', 'themes/hexo-theme-cola-master/source/imgs/about', 'icon-guanyuwomen']
  - ['我的工具', 'themes/hexo-theme-cola-master/source/imgs/tools', 'icon-gongju']

# 友情连接：头像、名字、链接
links:
 - ['https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg', 'Hexo.', 'https://hexo.io/zh-cn/']

# 右侧栏公告
notice: 大家好！这里是爱发电的猛男妙妙屋，微信公众号“爱发电的猛男妙妙屋”。在我的blog中，我将会分享一些大学日常生活以及阿里云盘的资源。

# 右侧音乐列表：歌名、作者、链接、封面
musics:
#   - ['安河桥', '宋冬野', 'http://ting6.yymp3.net:82/new25/songdongye/11.mp3', 'https://img2.baidu.com/it/u=1260056724,1076343118&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500']
  - ['花海', '周杰伦', 'music/周杰伦 - 花海.mp3']
  - ['起风了', '吴青峰', 'music/吴青峰 - 起风了.mp3']

# 个人介绍
likes:
  - 姓名：胡猛
  - 年龄：20
  - 性别：♂
  - 家乡：河南省周口市商水县
  - 现居住地：河南省焦作市武陟县
  - 职业：黄河交通学院交通运输专业的学生
  - 喜欢：学习，打游戏，学习，打游戏

# 工具配置：封面，标题，介绍，链接
tools:
  # - ['https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/30e94204580a4dbd83a64d4f91a9a6e5~tplv-k3u1fbpfcp-no-mark:240:240:240:160.awebp?', 'PNG图片压缩器', '这是一款无损压缩PNG图片的在线工具，可以童工上传或拖动来批量压缩图片并打包下载', 'http://1.14.43.39:5000/']
  - ['https://coke-cola.gitee.io/resume-page/assets/dark-f439b888.jpeg', '在线简历生成器', '一个免费的在线简历生成工具', 'https://coke-cola.gitee.io/resume-page/#/']

# 右侧栏网站信息
copyright: 豫ICP备2023005384号-1


# 是否开启文章评论 Valine:https://valine.js.org/configuration.htm
comments:
  enable: true
  appId: 'Pf8zCXGEH1qsprnWfikVVujL-gzGzoHsz'
  appKey: 'qOqoiUHhH1TGtLRUYURkLRQX'
  placeholder: '请留下你宝贵的意见吧~'
  meta: ['nick']
  recordIP: true
  visitor: true
  enableQQ: true

# 纪念模式 none: 不设置 all：全部置灰 index: 首页置灰
gray: none

# 日志篇幅超过1000字后隐藏（最大高度为1000px)，1000可为任意数值
log_text_num: 1000

# 版本号
version: 1.0.2
